# Generated by Django 6.1.1 on 2026-10-03 06:02

import courts.models
import datetime
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0002_btree_gist"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("kind", "exclusive"), ("status", "confirmed")),
                expressions=[
                    (
                        courts.models.TsTzRange(
                            "start",
                            "end",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("court", "="),
                ],
                name="no_overlapping_court_bookings",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "exclusive"), _negated=True),
                    (
                        "end",
                        django.db.models.expressions.CombinedExpression(
                            models.F("start"),
                            "+",
                            models.Value(datetime.timedelta(seconds=3600)),
                        ),
                    ),
                    _connector="OR",
                ),
                name="whole_court_booking_is_one_hour",
            ),
        ),
    ]
