# Generated by Django 6.1.1 on 2026-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0003_booking_no_overlapping_court_bookings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
