# Generated by Django 6.1.1 on 2026-10-03 09:15

import courts.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0004_booking_is_paid_booking_payment_method"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="no_overlapping_court_bookings",
        ),
        migrations.AddField(
            model_name="booking",
            name="hold_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Only for status 'held'", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("held", "Held"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                ],
                default="confirmed",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("kind", "exclusive"), ("status__in", ["held", "confirmed"])
                ),
                expressions=[
                    (
                        courts.models.TsTzRange(
                            "start",
                            "end",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("court", "="),
                ],
                name="no_overlapping_court_bookings",
            ),
        ),
    ]
