# Generated by Django 6.1.1 on 2026-10-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0005_remove_booking_no_overlapping_court_bookings_and_more"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("offered", "Offered"),
                            ("done", "Done"),
                            ("expired", "Expired"),
                            ("left", "Left"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_offers",
                        to="courts.booking",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courts.court"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["waiting", "offered"])),
                        fields=("member", "court", "start"),
                        name="one_live_waitlist_entry_per_slot",
                    )
                ],
            },
        ),
    ]
