# Generated by Django 6.1.1 on 2026-10-03 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("razorpay_order_id", models.CharField(blank=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("court", "Court"),
                            ("shop", "Shop"),
                            ("bar", "Bar"),
                            ("membership", "Membership"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount_paise", models.PositiveIntegerField()),
                ("status", models.CharField(default="created", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("customer_name", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=200)),
                (
                    "amount_paise",
                    models.PositiveIntegerField(help_text="Amount before GST"),
                ),
                ("gst_pct", models.PositiveSmallIntegerField(default=18)),
                ("is_paid", models.BooleanField(default=False)),
                ("issued_on", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("expense", "Expense"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("court", "Court"),
                            ("shop", "Shop"),
                            ("bar", "Bar"),
                            ("membership", "Membership"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "Upi"),
                            ("online", "Online"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount_paise", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.payment",
                    ),
                ),
            ],
        ),
    ]
