# Generated by Django 6.1.1 on 2026-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="reference_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="Id of the booking/order/membership", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference_id",
            field=models.PositiveIntegerField(
                default=0, help_text="Id of the booking/order this pays for"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ledger",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("upi", "Upi"),
                    ("online", "Online (Razorpay)"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("created", "Created"), ("paid", "Paid")],
                default="created",
                max_length=10,
            ),
        ),
    ]
