# Generated by Django 6.1.1 on 2026-10-03 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_ledger_reference_id_payment_paid_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledger",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
