# Generated by Django 6.1.1 on 2026-10-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_ledger_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer_gstin",
            field=models.CharField(
                blank=True, help_text="For business customers", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_method",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="source",
            field=models.CharField(
                choices=[
                    ("court", "Court"),
                    ("shop", "Shop"),
                    ("bar", "Bar"),
                    ("membership", "Membership"),
                ],
                default="membership",
                max_length=12,
            ),
        ),
    ]
