# Generated by Django 6.1.1 on 2026-10-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_invoice_customer_gstin_invoice_paid_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_paise",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
