# Generated by Django 6.1.1 on 2026-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_customer_phone_order_delivery_fee_paise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, db_default="", default=""),
        ),
    ]
