# Generated by Django 6.1.1 on 2026-10-03 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="discount_paise",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tab",
            name="total_paise",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("staff",),
                name="one_open_shift_per_staff",
            ),
        ),
        migrations.AddConstraint(
            model_name="tab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("table",),
                name="one_open_tab_per_table",
            ),
        ),
    ]
