# Generated by Django 6.1.1 on 2026-10-03 14:29

from django.db import migrations, models

# The cafe became pure vegetarian. Items are renamed in place rather than deleted, because past
# bills (TabLine) point at them and the database protects that link.
VEG_SWAPS = {
    "Chicken Burger": "Aloo Tikki Burger",
    "Butter Chicken Meal": "Paneer Butter Masala Meal",
}


def make_menu_veg(apps, schema_editor):
    MenuItem = apps.get_model("bar", "MenuItem")
    for old, new in VEG_SWAPS.items():
        if not MenuItem.objects.filter(name=new).exists():
            MenuItem.objects.filter(name=old).update(name=new)


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0002_tab_discount_paise_tab_total_paise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, db_default="", default=""),
        ),
        migrations.RunPython(make_menu_veg, migrations.RunPython.noop),
    ]
