# Generated by Django 6.1.1 on 2026-10-03 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "price_paise",
                    models.PositiveIntegerField(
                        help_text="Membership fee for one period"
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=365)),
                ("court_discount_pct", models.PositiveSmallIntegerField(default=0)),
                (
                    "free_court_hours_per_month",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("shop_discount_pct", models.PositiveSmallIntegerField(default=0)),
                ("bar_discount_pct", models.PositiveSmallIntegerField(default=0)),
                ("daily_booking_limit", models.PositiveSmallIntegerField(default=2)),
                ("junior_only", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField()),
                ("emergency_contact", models.CharField(blank=True, max_length=120)),
                ("whatsapp_opt_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wards",
                        to="members.member",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cancelled", models.BooleanField(default=False)),
                ("reminder_sent_on", models.DateField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="members.member",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.plan"
                    ),
                ),
            ],
        ),
    ]
