# Generated by Django 6.1.1 on 2026-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(
                blank=True, help_text="Email text (WhatsApp uses the approved template)"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="notification",
            name="to",
            field=models.CharField(
                default="", help_text="Phone number or email address", max_length=254
            ),
            preserve_default=False,
        ),
    ]
